### ISSUE TITLE
VSL query does not work?

### ISSUE THREAD

**Issue by iwikus** [varnish/varnishlog-json#1]
I am trying to setup logging backend errors into openobserve. When I use this query as example:

<pre>varnishlog  -q "BerespStatus >= 500"</pre>

it logs backend errors, but when using varnishlog-json with same condition
<pre>./varnishlog-json -q "BerespStatus >= 500"</pre>

there is no output.  This not implemented yet or some bug?

**Comment by gquintard** [comment]
Hi @iwikus!

Most likely, this is because `varnishlog-json`, like `varnishncsa` will by default filter client transactions.

Your query targets backend transactions, so the query doesn't find any client request matching it.

Can you try running the command again with `-b` or `-bc` please?

**Comment by iwikus** [comment]
Thanks, with this option(s) it is working.
